export { default as Currency } from './Currency'
//export { default as CheckBox } from './CheckBox';
export { default as Form } from './Form'
export { default as Submit } from './Submit'
export { default as Field } from './Field'
export { default as ImgInput } from './ImgInput'
//export { default as Error } from './Error';
//export { default as Select } from './Select'
//export { default as Phone } from './Phone';
